platform: android
platformName: android
tags: set0
automationName: UiAutomator2
platformVersion: '16.0'
deviceName: emulator-5554
remote_url: http://127.0.0.1:4723
system_port: 18000
udid: emulator-5554
app: /Users/realdoppio/Downloads/gother.apk